include ../../../build/variables.mk

PROJECT=crankysim
MMCU=atmega168
#F_CPU=8000000
F_CPU=16000000
SOURCES=main.c
#COMPILER=avr-gcc
AVRDUDE_PORT=/dev/tty.usbserial-A8007UF6

# You can also define anything here and it will override 
# the definitions in variables.mk

#AVRDUDE_PROGRAMMER=usbtiny

include ../../../build/targets.mk
