include ../../build/variables.mk

PROJECT=ws2811
MMCU=atmega328
F_CPU=20000000
SOURCES=main.c

HFUSE = 0xD9
LFUSE = 0xE2

# You can also define anything here and it will override 
# the definitions in variables.mk

AVRDUDE_PROGRAMMER=usbtiny

include ../../build/targets.mk
