include ../../build/variables.mk

PROJECT=serial_test
MMCU=atmega328p
F_CPU=16000000
SOURCES=main.c lib/serial/serial.c lib/serial/serial_sync_tx.c lib/serial/serial_sync_rx.c


PROGRAMMER=usbasp

include ../../build/targets.mk
