include ../../build/variables.mk

PROJECT=Quadcopter_Pilot
MMCU=atmega168
F_CPU=20000000
SOURCES=main.c

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk