include ../../../build/variables.mk

PROJECT=TimerTest
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/timer/timer_0.c lib/serial/serial_asynchronous.c

# You can also define anything here and it will override
# the definitions in variables.mk

include ../../../build/targets.mk

