include ../../build/variables.mk

PROJECT=Blinkenlights
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/shiftcpp/shift.cpp
COMPILER=avr-g++

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
