include ../../build/variables.mk

PROJECT=twowire
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/TwoWire/TwoWire.cpp lib/serial/serial.c lib/serial/serial_sync_tx.c lib/serial/serial_sync_rx.c
COMPILER=avr-g++


include ../../build/targets.mk

