include ../../build/variables.mk

PROJECT=glcd
MMCU=atmega168
F_CPU=8000000
SOURCES=main.c lib/glcd/glcd_st7565r.c lib/glcd/draw.c lib/glcd/fonts/medium.c lib/glcd/fonts/large.c
PROGRAMMER=usbtiny

HFUSE=0xDF
LFUSE=0xE2


include ../../build/targets.mk

