include ../../../../../build/variables.mk

PROJECT=psx-test
MMCU=atmega168
F_CPU=16000000
SOURCES=psx_test.c psx_hardware.c ../../../lib/serial/serial.c ../../../lib/psx/psx.c ../../../lib/timer/timer.c

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../../../../build/targets.mk