include ../../build/variables.mk

PROJECT=button
MMCU=atmega168
#F_CPU=8000000
F_CPU=16000000
SOURCES=main.cpp lib/button/button.cpp
COMPILER=avr-g++

# You can also define anything here and it will override 
# the definitions in variables.mk

#AVRDUDE_PROGRAMMER=usbtiny

include ../../build/targets.mk
