include ../build/variables.mk
include time.mk

PROJECT=ring60
MMCU=atmega328
F_CPU=20000000
SOURCES=main.c $(time_a_c_sources) $(time_a_asm_sources) 

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../build/targets.mk
