include ../../build/variables.mk

PROJECT=piezo
MMCU=atmega168
F_CPU=20000000
SOURCES=main.c 
AVRDUDE_PROGRAMMER=usbtiny

# You can also define anything here and it will override 
# the definitions in variables.mk

HFUSE=0xDD
LFUSE=0xF7

include ../../build/targets.mk
