include build/variables.mk

PROJECT=rescue
MMCU=atmega168
F_CPU=16000000
SOURCES=rescue.c

# You can also define anything here and it will override 
# the definitions in variables.mk

include build/targets.mk
