include ../../variables.mk

PROJECT=Skeleton
MMCU=atmega644
F_CPU=16000000
SOURCES=main.c

# You can also define anything here and it will override 
# the definitions in variables.mk

AVRDUDE_PROGRAMMER=usbtiny

include ../../targets.mk
