include ../../../build/variables.mk

PROJECT=serial_test
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/serial/serial_synchronous.c

# You can also define anything here and it will override 
# the definitions in variables.mk

#AVRDUDE_PROGRAMMER=stk500

include ../../../build/targets.mk
