include ../../../build/variables.mk

PROJECT=protocol_test
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c protocol.c lib/serial/serial.c lib/serial/serial_sync_tx.c lib/serial/serial_async_rx.c

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../../build/targets.mk
