include ../../variables.mk

PROJECT=Skeleton
MMCU=attiny13
F_CPU=8000000
SOURCES=main.c

# You can also define anything here and it will override 
# the definitions in variables.mk

AVRDUDE_PROGRAMMER=usbtiny

include ../../targets.mk
