include ../../build/variables.mk

PROJECT=Blinkenlights
MMCU=atmega644p
F_CPU=20000000
SOURCES=main.c lib/timer/timer.c lib/shift/shift.c
AVRDUDE_PROGRAMMER=usbtiny

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
