include ../../../../../build/variables.mk

PROJECT=LYPR530_test
MMCU=atmega168
F_CPU=16000000
SOURCES=LYPR530_test.c gyro_LYPR530.c ../../../lib/serial/serial_synchronous.c ../../../lib/timer/timer.c

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../../../../build/targets.mk
