include ../../build/variables.mk

PROJECT=hd44780
MMCU=atmega32u2
F_CPU=16000000
SOURCES=main.c lib/Hd44780/Hd44780.cpp lib/Hd44780/Hd44780_Direct.cpp
PROGRAMMER=dfu
COMPILER=avr-g++


include ../../build/targets.mk
