include ../../../../../build/variables.mk

PROJECT=pwm_test
MMCU=atmega168
F_CPU=16000000
SOURCES=pwm_test.c esc_pwm.c ../../../lib/pwm/pwm.c

# You can also define anything here and it will override 
# the definitions in variables.mk
#CDEFS=-DF_CPU=$(F_CPU) -DPWM_MAX_PINS=3

include ../../../../../build/targets.mk
