include ../../../build/avr/variables.mk

PROJECT=crankysim
MMCU=atmega32u2
F_CPU=16000000
SOURCES=main.c lib/usb/rawhid.c
AVRDUDE_PROGRAMMER=dfu
COMPILER=avr-g++


include ../../../build/avr/targets.mk
