include ../../build/variables.mk

PROJECT=PSX
MMCU=atmega644p
F_CPU=8000000
SOURCES=main.c lib/psx/psx.c lib/serial1/serial1.c lib/serial1/serial1_sync_tx.c lib/serial1/serial1_sync_rx.c
PROGRAMMER=usbtiny


include ../../build/targets.mk

