include ../../../build/variables.mk

PROJECT=manchester_test
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/manchester/manchester_sync_rx.c lib/manchester/manchester_sync_tx.c

# You can also define anything here and it will override 
# the definitions in variables.mk

#AVRDUDE_PROGRAMMER=usbtiny

include ../../../build/targets.mk
