include ../../../build/variables.mk

PROJECT=cranky
MMCU=atmega168
#F_CPU=8000000
F_CPU=20000000
SOURCES=main.c
#COMPILER=avr-gcc

# You can also define anything here and it will override 
# the definitions in variables.mk

AVRDUDE_PROGRAMMER=usbtiny

include ../../../build/targets.mk
