include ../../../build/variables.mk

PROJECT=manchester_test_rx
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/manchester/manchester_sync_rx.c lib/serial/serial.c lib/serial/serial_sync_rx.c lib/serial/serial_sync_tx.c


#PROGRAMMER=usbtiny

include ../../../build/targets.mk
