include ../../../build/variables.mk

PROJECT=protocol_test
MMCU=atmega644
F_CPU=20000000
SOURCES=main.c protocol.c lib/serial/serial.c lib/serial/serial_sync_tx.c lib/serial/serial_async_rx.c


PROGRAMMER=usbtiny

include ../../../build/targets.mk
