include ../../build/variables.mk

PROJECT=piezo
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c 
#AVRDUDE_PROGRAMMER=usbtiny

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
