include ../../build/variables.mk

PROJECT=shiftcpp
MMCU=atmega168
F_CPU=16000000
SOURCES=main.cpp lib/ShiftRegister/ShiftRegister.cpp
COMPILER=avr-g++

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
