include ../../../build/variables.mk

PROJECT=manchester_test_tx
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/manchester/manchester_sync_tx.c


#PROGRAMMER=usbtiny

include ../../../build/targets.mk
