include ../../build/variables.mk

PROJECT=piezo
MMCU=attiny13
F_CPU=10000000
SOURCES=main.c 

# You can also define anything here and it will override 
# the definitions in variables.mk

AVRDUDE_PROGRAMMER=usbtiny

include ../../build/targets.mk

