include ../../build/variables.mk

PROJECT=Skeleton
MMCU=atmega328p
F_CPU=16000000
SOURCES=main.c
AVRDUDE_PROGRAMMER=arduino

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
