include ../../build/variables.mk

PROJECT=ols-scope
MMCU=atmega48
F_CPU=20000000
SOURCES=main.c lib/analog/analog_synchronous.c
PROGRAMMER=usbtiny

HFUSE=0xDF
LFUSE=0x7F
EFUSE=0xFF

# CDEFS+=-DADC_SLEEP_MODE


include ../../build/targets.mk
