include ../../../build/variables.mk

PROJECT=Blinkenlights
MMCU=attiny13
F_CPU=10000000
SOURCES=main.c lib/shift/shift.c

# You can also define anything here and it will override 
# the definitions in variables.mk

AVRDUDE_PROGRAMMER=usbtiny

include ../../../build/targets.mk

