include ../../../../build/variables.mk

PROJECT=buzzer
MMCU=atmega644
F_CPU=8000000
SOURCES=buzzer_test.c status_buzzer.c
PROGRAMMER=usbtiny

# You can also define anything here and it will override
# the definitions in variables.mk

include ../../../../build/targets.mk
