include ../../build/variables.mk

PROJECT=blinkylights
MMCU=atmega32u4
F_CPU=16000000
SOURCES=main.c
AVRDUDE_PROGRAMMER=dfu

# You can also define anything here and it will override 
# the definitions in variables.mk
LFUSE=0xDE
HFUSE=0xD9
EFUSE=0xF3

include ../../build/targets.mk
