#ifndef PINS_H
#define PINS_H

//The pin definitions for ATMega644P

#define PORT_LED_SHIFT_DATA		PORTD
#define PIN_LED_SHIFT_DATA		PIND4
#define PORT_LED_SHIFT_CLOCK	PORTD
#define PIN_LED_SHIFT_CLOCK		PIND5
#define PORT_LED_SHIFT_LATCH	PORTD
#define PIN_LED_SHIFT_LATCH		PIND6

#define PORT_PSX_CLOCK			PORTB	// blue
#define PIN_PSX_CLOCK			PINB0
#define PORT_PSX_DATA			PORTB	// brown
#define PIN_PSX_DATA			PINB1
#define PORT_PSX_COMMAND		PORTB	// orange
#define PIN_PSX_COMMAND			PINB2
#define PORT_PSX_ATTENTION		PORTB	// yellow
#define PIN_PSX_ATTENTION		PINB3

#define PORT_LED_ARMED			PORTC
#define PIN_LED_ARMED			PINC2
#define PORT_LED_CRUISE			PORTC
#define PIN_LED_CRUISE			PINC3

#endif
