include ../../build/variables.mk

PROJECT=blinkylights
MMCU=attiny84
F_CPU=8000000
SOURCES=main.c
AVRDUDE_PROGRAMMER=avrispmkII

# You can also define anything here and it will override 
# the definitions in variables.mk
#LFUSE=0xDE
#HFUSE=0xD9
#EFUSE=0xF3

include ../../build/targets.mk
