include ../../../build/variables.mk

PROJECT=Oscilloscope
MMCU=atmega644
F_CPU=20000000
SOURCES=main.c lib/timer/timer.c lib/serial/serial.c lib/sd-card/sd_raw.c

# You can also define anything here and it will override 
# the definitions in variables.mk

AVRDUDE_PROGRAMMER=usbtiny

include ../../../build/targets.mk

