include ../../build/variables.mk

PROJECT=button
MMCU=atmega168
#F_CPU=8000000
F_CPU=16000000
SOURCES=main.cpp lib/button/button.cpp lib/serial/serial.c lib/serial/serial_sync_rx.c lib/serial/serial_sync_tx.c
COMPILER=avr-g++


#PROGRAMMER=usbtiny

include ../../build/targets.mk
