#ifndef UNIVERSAL_CONTROLLER_CLIENT_H
#define UNIVERSAL_CONTROLLER_CLIENT_H

#define CONTROLLER_EVENT_MASK	0xF0

#define CONTROLLER_BUTTON_EVENT_PRESS	0xF0
#define CONTROLLER_BUTTON_EVENT_RELEASE	0xE0

#define CONTROLLER_STICK_SIDE_MASK		0x80
#define CONTROLLER_STICK_SIDE_LEFT		0x00
#define CONTROLLER_STICK_SIDE_RIGHT		0x80

#define CONTROLLER_STICK_AXIS_MASK		0x40
#define CONTROLLER_STICK_AXIS_X			0x00
#define CONTROLLER_STICK_AXIS_Y			0x40

#define CONTROLLER_STICK_

#define CONTROLLER_SELECT	0x00
#define CONTROLLER_LEFT3	0x01
#define CONTROLLER_RIGHT3	0x02
#define CONTROLLER_START	0x03
#define CONTROLLER_PADUP	0x04
#define CONTROLLER_PADRIGHT	0x05
#define CONTROLLER_PADDOWN	0x06
#define CONTROLLER_PADLEFT	0x07
#define CONTROLLER_LEFT2	0x08
#define CONTROLLER_RIGHT2	0x09
#define CONTROLLER_LEFT1	0x0A
#define CONTROLLER_RIGHT1	0x0B
#define CONTROLLER_TRIANGLE	0x0C
#define CONTROLLER_CIRCLE	0x0D
#define CONTROLLER_CROSS	0x0E
#define CONTROLLER_SQUARE	0x0F

#endif