include ../../build/variables.mk

PROJECT=PSX
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/psx/psx.c lib/serial/serial_synchronous.c

# You can also define anything here and it will override
# the definitions in variables.mk

include ../../build/targets.mk

