include ../../../build/variables.mk

PROJECT=accel
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/i2c/i2c_master.c lib/serial/serial_synchronous.c 

# You can also define anything here and it will override
# the definitions in variables.mk

include ../../../build/targets.mk

