include ../../build/variables.mk

PROJECT=usbserial
MMCU=atmega32u2
F_CPU=16000000
SOURCES=main.c lib/usb/serial/serial.c
AVRDUDE_PROGRAMMER=dfu

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
