include ../../../build/avr/variables.mk

PROJECT=cranky
MMCU=atmega48
#F_CPU=8000000
F_CPU=20000000
SOURCES=main.c
#COMPILER=avr-gcc

# You can also define anything here and it will override 
# the definitions in variables.mk

HFUSE=0xDF
LFUSE=0xDF

AVRDUDE_PROGRAMMER=usbtiny

include ../../../build/avr/targets.mk
