include ../../build/variables.mk

PROJECT=Skeleton
MMCU=atmega32u2
F_CPU=16000000
SOURCES=main.c
AVRDUDE_PROGRAMMER=dfu

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
