include ../../../../../build/variables.mk

PROJECT=pwm_test
MMCU=atmega168
F_CPU=16000000
SOURCES=pwm_test.c esc_pwm.c lib/pwm/pwm.c

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../../../../build/targets.mk
