include ../../build/variables.mk

PROJECT=PSX
MMCU=atmega644p
F_CPU=20000000
SOURCES=main.c lib/psx/psx.c lib/serial1/serial1.c lib/serial1/serial1_sync_tx.c lib/serial1/serial1_sync_rx.c
AVRDUDE_PROGRAMMER=usbtiny

# You can also define anything here and it will override
# the definitions in variables.mk

include ../../build/targets.mk

