include ../../../../../build/variables.mk

PROJECT=MMA7455L_test
MMCU=atmega168
F_CPU=16000000
SOURCES=MMA7455L_test.c MMA7455L_hardware.c ../../../lib/serial/serial.c ../../../lib/timer/timer.c

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../../../../build/targets.mk