include ../../../build/variables.mk

PROJECT=protocol_test
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c protocol.c lib/serial/serial.c lib/serial/serial_sync_tx.c lib/serial/serial_async_rx.c


include ../../../build/targets.mk
