include ../../build/variables.mk

PROJECT=analog
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/analog/analog_asynchronous.c lib/serial/serial_synchronous.c

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
