include ../../build/variables.mk

PROJECT=shift
MMCU=atmega644p
F_CPU=8000000
SOURCES=main.c lib/shiftcpp/shift.cpp
COMPILER=avr-g++
AVRDUDE_PROGRAMMER=usbtiny

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
