PROJECT=kubkar_timer
MMCU=atmega48
F_CPU=20000000
SOURCES=main.cpp lib/Button/Buttons.cpp lib/analog/analog_synchronous.c
PROGRAMMER=usbtiny
COMPILER=avr-g++

LFUSE=0xF7
HFUSE=0xDF
EFUSE=0x01

include build/targets.mk
