PROJECT=kubkar_timer
MMCU=atmega328
F_CPU=16000000
SOURCES=main.cpp lib/Button/Buttons.cpp lib/analog/analog_synchronous.c
PROGRAMMER=arduino
COMPILER=avr-g++
CDEFS+=-DTIMER_BITS=32 

include build/targets.mk
