include ../../build/variables.mk

PROJECT=analog
MMCU=atmega644p
F_CPU=20000000
SOURCES=main.c lib/analog/analog_asynchronous.c lib/serial/serial_sync_tx.c lib/serial/serial_sync_rx.c lib/serial/serial.c
AVRDUDE_PROGRAMMER=usbtiny


# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
