PROJECT=PSXController
MMCU=atmega48
F_CPU=8000000
PROGRAMMER=usbtiny

HFUSE=0xDF
LFUSE=0xE2

# You can also define anything here and it will override
# the definitions in variables.mk
include ../../../build/avr.mk

