include ../../build/variables.mk

PROJECT=piezo
MMCU=attiny13
F_CPU=4800000
SOURCES=main.c 

# You can also define anything here and it will override 
# the definitions in variables.mk

AVRDUDE_PROGRAMMER=usbtiny

HFUSE=0xFB
LFUSE=0x79

include ../../build/targets.mk

