include ../build/variables.mk

PROJECT=drummaster
MMCU=atmega168
F_CPU=16000000
SOURCES=drummaster.c

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../build/targets.mk
