include ../../build/variables.mk

PROJECT=glcd
MMCU=atmega168
F_CPU=6000000
SOURCES=main.c lib/glcd/glcd.c 
AVRDUDE_PROGRAMMER=usbtiny

HFUSE=0xDF
LFUSE=0xF7

# You can also define anything here and it will override
# the definitions in variables.mk

include ../../build/targets.mk

