include ../../build/variables.mk

PROJECT=rawhid
MMCU=atmega32u2
F_CPU=16000000
SOURCES=main.c lib/usb/rawhid.c
AVRDUDE_PROGRAMMER=dfu
COMPILER=avr-g++

# You can also define anything here and it will override 
# the definitions in variables.mk

include ../../build/targets.mk
