include ../../../build/variables.mk

PROJECT=serial_test
MMCU=atmega168
F_CPU=16000000
SOURCES=main.c lib/serial/serial.c lib/serial/serial_sync_tx.c lib/serial/serial_sync_rx.c


#PROGRAMMER=usbtiny

include ../../../build/targets.mk
